### ISSUE TITLE
Json error

### ISSUE THREAD

**Issue by frknky92** [merdok/homebridge-webos-tv#114]
Hello,
How can ı solved this problem
I have a problem but where I don't know json
Thank you for your supports,

Error;
FURKANs-Mac:~ furkankaya$ homebridge
[2/1/2019, 8:52:26 PM] There was a problem reading your config.json file.
[2/1/2019, 8:52:26 PM] Please try pasting your config.json file here to validate it: http://jsonlint.com
[2/1/2019, 8:52:26 PM] 
/usr/local/lib/node_modules/homebridge/lib/server.js:214
    throw err;
    ^

SyntaxError: Unexpected token { in JSON at position 141
    at JSON.parse (<anonymous>)
    at Server._loadConfig (/usr/local/lib/node_modules/homebridge/lib/server.js:208:19)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:56:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:30:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)

My config.json file;

  "accessories": [
    {
      "accessory": "webostv",
      "name": "My webOS tv",
      "ip": "tvipaddress",
      "mac": "tvmacaddress",
      "keyFile": "/home/pi/.homebridge/lgtvKeyFile",
      "pollingInterval": 10,
      "tvService": true,
      "inputs": [
          {
            "appId": "com.webos.app.livetv",
            "name": "Live TV"
          },
          {
            "appId": "com.webos.app.hdmi1",
            "name": "Chromecast"
          },
          {
            "appId": "youtube.leanback.v4",
            "name": "YouTube"
          },
          {
            "appId": "com.webos.app.photovideo",
            "name": "Photo Video"
          }
      ],
      "volumeControl": false,
      "channelControl": false,
      "mediaControl": false
    }
  ]
}

**Comment by merdok** [comment]
Just use the link specified to validate your json... You can also use some online json beautifier to make it more readable.

**Comment by merdok** [comment]
You missing a `{ `at the begining.
