### ISSUE TITLE
Error since upgrade to Homebridge 0.4.50

### ISSUE THREAD

**Issue by siobhanellis** [merdok/homebridge-webos-tv#158]
The plugin still seems to work, but this is what I get in my Homebridge log, just after I turned on the TV.

[08/06/2019, 3:33:48 pm] [TV] webOS - connected to TV
[08/06/2019, 3:33:48 pm] [TV] webOS - audio status changed
[08/06/2019, 3:33:48 pm] [TV] webOS - current volume: 0
[08/06/2019, 3:33:48 pm] [TV] webOS - muted: No
[08/06/2019, 3:33:48 pm] [TV] webOS - current channel status changed
[08/06/2019, 3:33:48 pm] [TV] webOS - current channel: undefined, undefined
[08/06/2019, 3:33:48 pm] [TV] webOS - sound output changed
[08/06/2019, 3:33:48 pm] [TV] webOS - current sound output: external_speaker
[08/06/2019, 3:33:48 pm] [TV] webOS - app launched, current appId: com.webos.app.hdmi2
[08/06/2019, 3:34:03 pm] [TV] webOS - Error: Sec-WebSocket-Accept header from server didn't match expected value of M6/Gf5Q7lY20aHeYr5C6/7Uk1tM=
    at WebSocketClient.failHandshake (/usr/local/lib/node_modules/homebridge-webos-tv/node_modules/websocket/lib/WebSocketClient.js:339:32)
    at WebSocketClient.validateHandshake (/usr/local/lib/node_modules/homebridge-webos-tv/node_modules/websocket/lib/WebSocketClient.js:326:14)
    at ClientRequest.handleRequestUpgrade (/usr/local/lib/node_modules/homebridge-webos-tv/node_modules/websocket/lib/WebSocketClient.js:261:14)
    at ClientRequest.emit (events.js:196:13)
    at Socket.socketOnData (_http_client.js:485:11)
    at Socket.emit (events.js:196:13)
    at addChunk (_stream_readable.js:290:12)
    at readableAddChunk (_stream_readable.js:271:11)
    at Socket.Readable.push (_stream_readable.js:226:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:166:17)

**Comment by merdok** [comment]
This error should be ok. This happens from time to time when a packet is corrupted.
