### ISSUE TITLE
Cannot run homebridge with webos.tv plugin

### ISSUE THREAD

**Issue by Gejza75** [merdok/homebridge-webos-tv#173]
Hi everybody,

Can anyone help with issue on raspberry pi? I am trying to configure and run homebridge with webos-tv plugin on my raspberry pi, but without success. I still get an error:

**TypeError: Cannot read property 'indexOf' of undefined
    at API.accessory (/usr/local/lib/node_modules/homebridge/lib/api.js:50:11)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:297:42)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:91:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)**

Any ideas, how to solve this, or what is wrong?
Thanks a lot to everyone!!

**Comment by merdok** [comment]
I do not think that this has anything to do with this plugin. At least the error which you posted does not look like that...

**Comment by Gejza75** [comment]
Solved now. Mixture of mistakes made. Thanks.
