### ISSUE TITLE
Second tv not responding

### ISSUE THREAD

**Issue by gussyboy** [merdok/homebridge-webos-tv#226]
I got two LG tv's in my house;

LG UH652T - software version 05.50.80
LG UJ654T - software version 05.80.55

I've had them both running on homebridge fine previously but i've since updated to use the latest vesion of homebridge and homebridge-webos-tv, via the platform model.

I've been able to get the two tv's appearing in homekit but the second one in the array appears and never responds. I feel it has to be related to some form of configuartion on the tv?

The thing I notice is when turning on **Mobile TV On** it doesn't give me a simple on or off option but instead the option to turn on via Wi-Fi or Bluetooth. Neither of my TV's are connected by Wi-Fi, they're both hardwired via ethernet.

I don't get asked to allow connection to the tv either, which is clearly a issue.

Any ideas whats going wrong?

Heres my config:

```
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
    "description": "Homebridge for Homekit.",
    "accessories": [],
    "platforms": [
        {
            "platform": "webostv",
            "devices": [
                {
                    "name": "webOS TV UH652T",
                    "ip": "192.168.1.109",
                    "mac": "14:c9:13:30:6c:97",
                    "keyFile": "/homebridge/lgtvKeyFile",
                    "inputs": [
                        {
                            "appId": "com.webos.app.hdmi2",
                            "name": "Apple TV"
                        },
                        {
                            "appId": "com.webos.app.hdmi1",
                            "name": "Foxtel"
                        }
                    ],
                    "showInputButtons": false,
                    "volumeControl": false,
                    "channelControl": false,
                    "mediaControl": false
                },
                {
                    "name": "webOS TV UJ654T",
                    "ip": "192.168.1.124",
                    "mac": "38:8c:50:c8:6a:38",
                    "keyFile": "/homebridge/lgtvKeyFile2",
                    "inputs": [
                        {
                            "appId": "com.webos.app.hdmi1",
                            "name": "Apple TV"
                        },
                        {
                            "appId": "com.webos.app.livetv",
                            "name": "Live TV"
                        }
                    ],
                    "showInputButtons": false,
                    "volumeControl": false,
                    "channelControl": false,
                    "mediaControl": false
                }
            ]
        }
    ]
}
```

**Comment by merdok** [comment]
Did you follow the instructions [adding the tv to home app when using platform](https://github.com/merdok/homebridge-webos-tv#adding-the-tv-to-home-app-when-using-platform)? The process od adding a tv when using a platform is different from the accessory process. Ju

**Comment by gussyboy** [comment]
Yes, as I mentioned they are both in the home app. The second one just isn’t reponding.

**Comment by merdok** [comment]
Maybe your tv is is in another network or you are missing something then...

**Comment by gussyboy** [comment]
Its on the same network

> The thing I notice is when turning on Mobile TV On it doesn't give me a simple on or off option but instead the option to turn on via Wi-Fi or Bluetooth. Neither of my TV's are connected by Wi-Fi, they're both hardwired via ethernet.

I think its related to the Mobile TV On feature, which seems to only be Wifi or bluetooth on this model

**Comment by merdok** [comment]
I do not think that this makes a difference, but you could try it out.

**Comment by agneevX** [comment]
Same issue here. Can't add the first TV anymore. Second one works.


HB debug logs:
```
[5/7/2020, 15:27:24] [webostv] Initializing webostv platform...
[5/7/2020, 15:27:24] [webostv] webOS - init - initializing devices
[5/7/2020, 15:27:24] [webostv] webOS - input names file does not exist
[5/7/2020, 15:27:24] [webostv] webOS - init - initializing device with name: Old Room TV
HAP-NodeJS WARNING: The accessory 'Old Room TV' is getting published with the characteristic 'Name' (of the AccessoryInformation service) not having a value set. This might prevent the accessory from being added to the Home App or leading to the accessory being unresponsive!
[5/7/2020, 15:27:24] [webostv] webOS - input names file does not exist
[5/7/2020, 15:27:24] [webostv] webOS - input names file does not exist
[5/7/2020, 15:27:24] [webostv] webOS - init - initializing device with name: New Room TV
HAP-NodeJS WARNING: The accessory 'New Room TV' is getting published with the characteristic 'Name' (of the AccessoryInformation service) not having a value set. This might prevent the accessory from being added to the Home App or leading to the accessory being unresponsive!
[5/7/2020, 15:27:24] [webostv] webOS - connecting to TV
[5/7/2020, 15:27:24] [webostv] webOS - connecting to TV
[5/7/2020, 15:27:24] [webostv] webOS - connected to TV, checking power status
[5/7/2020, 15:27:24] [webostv] webOS - power status - TV is On
[5/7/2020, 15:27:24] [webostv] webOS - connected to TV
[5/7/2020, 15:27:24] [webostv] webOS - subscribing to TV services
[5/7/2020, 15:27:24] [webostv] webOS - connecting to remote control socket
[5/7/2020, 15:27:24] [webostv] webOS - TV power status changed, status: 
[5/7/2020, 15:27:24] [webostv] webOS - app launched, current appId: netflix
[5/7/2020, 15:27:24] [webostv] webOS - audio status changed
[5/7/2020, 15:27:24] [webostv] webOS - current volume: 35
[5/7/2020, 15:27:24] [webostv] webOS - muted: No
[5/7/2020, 15:27:24] [webostv] webOS - current channel status changed
[5/7/2020, 15:27:24] [webostv] webOS - current channel: undefined, undefined
[5/7/2020, 15:27:24] [webostv] webOS - sound output changed
[5/7/2020, 15:27:24] [webostv] webOS - current sound output: headphone
[5/7/2020, 15:27:25] [webostv] webOS - requesting TV information
[5/7/2020, 15:27:25] [webostv] webOS - system info: 
{
  "features": {
    "3d": false,
    "dvr": true
  },
  "receiverType": "dvb",
  "modelName": "49UF690T-TC"
}
[5/7/2020, 15:27:25] [webostv] webOS - tv info file already exists, not saving!
...
```

**Comment by agneevX** [comment]
FWIW, the TVs are showing up in Config UI X:

<img width="336" alt="image" src="https://user-images.githubusercontent.com/19761269/81282077-52550400-9078-11ea-8979-5330ac8a25cc.png">

<img width="349" alt="image" src="https://user-images.githubusercontent.com/19761269/81282196-77e20d80-9078-11ea-89df-c38c283582e2.png">

**Comment by merdok** [comment]
It is a little bit hard to distinguish which log is from which tv. I guess i have to optimize first before we can make any assumptions...

**Comment by gussyboy** [comment]
So I set up homebridge from scratch to make sure I had latest versions of code and still getting the same error.

My config is:
```
{
    "bridge": {
        "name": "Homebridge",
        "username": "0E:B5:C2:72:6D:31",
        "port": 53037,
        "pin": "031-45-154"
    },
    "description": "Homebridge for Homekit.",
    "accessories": [],
    "platforms": [
        {
            "platform": "webostv",
            "devices": [
                {
                    "name": "webOS TV UH652T",
                    "ip": "192.168.1.109",
                    "mac": "14:c9:13:30:6c:97",
                    "keyFile": "/homebridge/lgtvKeyFile",
                    "inputs": [
                        {
                            "appId": "com.webos.app.hdmi2",
                            "name": "Apple TV"
                        },
                        {
                            "appId": "com.webos.app.hdmi1",
                            "name": "Foxtel"
                        }
                    ],
                    "showInputButtons": false,
                    "volumeControl": false,
                    "channelControl": false,
                    "mediaControl": false
                },
                {
                    "name": "webOS TV UJ654T",
                    "ip": "192.168.1.124",
                    "mac": "38:8c:50:c8:6a:38",
                    "keyFile": "/homebridge/lgtvKeyFile2",
                    "inputs": [
                        {
                            "appId": "com.webos.app.hdmi1",
                            "name": "Apple TV"
                        },
                        {
                            "appId": "com.webos.app.livetv",
                            "name": "Live TV"
                        }
                    ],
                    "showInputButtons": false,
                    "volumeControl": false,
                    "channelControl": false,
                    "mediaControl": false
                }
            ]
        }
    ]
}
```

The log from the first run was:
```
[5/8/2020, 12:15:49 PM] Homebridge is running on port 53037.                                      
[5/8/2020, 12:15:52 PM] [webostv] webOS - Error: connect EHOSTUNREACH 192.168.1.109:3000          
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {                             
  errno: 'EHOSTUNREACH',                                                                          
  code: 'EHOSTUNREACH',                                                                           
  syscall: 'connect',                                                                             
  address: '192.168.1.109',                                                                       
  port: 3000                                                                                      
}                                                                                                 
[5/8/2020, 12:15:52 PM] [webostv] webOS - Error: connect EHOSTUNREACH 192.168.1.124:3000          
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {                             
  errno: 'EHOSTUNREACH',                                                                          
  code: 'EHOSTUNREACH',                                                                           
  syscall: 'connect',                                                                             
  address: '192.168.1.124',                                                                       
  port: 3000                                                                                      
}                                                                                                 
[5/8/2020, 12:23:45 PM] [webostv] webOS - connected to TV                                         
[5/8/2020, 12:23:45 PM] [webostv] webOS - app launched, current appId: com.webos.app.hdmi2        
[5/8/2020, 12:23:45 PM] [webostv] webOS - audio status changed                                    
[5/8/2020, 12:23:45 PM] [webostv] webOS - current volume: 10                                      
[5/8/2020, 12:23:45 PM] [webostv] webOS - muted: No                                               
[5/8/2020, 12:23:45 PM] [webostv] webOS - current channel status changed                          
[5/8/2020, 12:23:45 PM] [webostv] webOS - current channel: undefined, undefined                   
[5/8/2020, 12:23:45 PM] [webostv] webOS - sound output changed                                    
[5/8/2020, 12:23:45 PM] [webostv] webOS - current sound output: tv_speaker                        
[5/8/2020, 12:23:50 PM] [webostv] webOS - disconnected from TV                                    
[5/8/2020, 12:24:02 PM] [webostv] webOS - connected to TV                                         
[5/8/2020, 12:24:02 PM] [webostv] webOS - app launched, current appId: com.webos.app.hdmi2        
[5/8/2020, 12:24:02 PM] [webostv] webOS - audio status changed                                    
[5/8/2020, 12:24:02 PM] [webostv] webOS - current volume: 10
[5/8/2020, 12:24:02 PM] [webostv] webOS - muted: No                                               
[5/8/2020, 12:24:48 PM] [webostv] webOS - Error: connect ECONNREFUSED 192.168.1.124:3000          
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {                             
  errno: 'ECONNREFUSED',                                                                          
  code: 'ECONNREFUSED',                                                                           
  syscall: 'connect',                                                                             
  address: '192.168.1.124',                                                                       
  port: 3000                                                                                      
}                                                                                                 
[5/8/2020, 12:24:54 PM] [webostv] webOS - Error: Sec-WebSocket-Accept header from server didn't ma
tch expected value of JKMce12hyULH8VeY/Th30GlGI+E=                                                
    at WebSocketClient.failHandshake (/usr/local/lib/node_modules/homebridge-webos-tv/node_modules
/websocket/lib/WebSocketClient.js:339:32)                                                         
    at WebSocketClient.validateHandshake (/usr/local/lib/node_modules/homebridge-webos-tv/node_mod
ules/websocket/lib/WebSocketClient.js:326:14)                                                     
    at ClientRequest.handleRequestUpgrade (/usr/local/lib/node_modules/homebridge-webos-tv/node_mo
dules/websocket/lib/WebSocketClient.js:261:14)                                                    
    at ClientRequest.emit (events.js:310:20)                                                      
    at Socket.socketOnData (_http_client.js:503:11)                                               
    at Socket.emit (events.js:310:20)                                                             
    at addChunk (_stream_readable.js:286:12)                                                      
    at readableAddChunk (_stream_readable.js:268:9)                                               
    at Socket.Readable.push (_stream_readable.js:209:10)                                          
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)                                  
[5/8/2020, 12:24:54 PM] [webostv] webOS - prompt for confirmation                                 
[5/8/2020, 12:24:57 PM] [webostv] webOS - prompt for confirmation                                 
[5/8/2020, 12:24:58 PM] [webostv] webOS - disconnected from TV 
[5/8/2020, 12:24:59 PM] [webostv] webOS - prompt for confirmation                                 
[5/8/2020, 12:25:04 PM] [webostv] webOS - prompt for confirmation                                 
[5/8/2020, 12:25:09 PM] [webostv] webOS - prompt for confirmation                                 
[5/8/2020, 12:25:14 PM] [webostv] webOS - prompt for confirmation                                 
[5/8/2020, 12:25:19 PM] [webostv] webOS - prompt for confirmation                                 
[5/8/2020, 12:25:24 PM] [webostv] webOS - prompt for confirmation                                 
[5/8/2020, 12:25:29 PM] [webostv] webOS - prompt for confirmation                                 
[5/8/2020, 12:25:34 PM] [webostv] webOS - prompt for confirmation                                 
[5/8/2020, 12:25:39 PM] [webostv] webOS - prompt for confirmation                                 
[5/8/2020, 12:25:44 PM] [webostv] webOS - prompt for confirmation                                 
[5/8/2020, 12:25:49 PM] [webostv] webOS - prompt for confirmation                                 
[5/8/2020, 12:25:54 PM] [webostv] webOS - prompt for confirmation                                 
[5/8/2020, 12:25:58 PM] [webostv] webOS - app switch service - Trying to launch com.webos.app.live
tv but TV is off, attempting to power on the TV                                                   
[5/8/2020, 12:25:59 PM] [webostv] webOS - prompt for confirmation                                 
[5/8/2020, 12:26:01 PM] [webostv] webOS - prompt for confirmation                                 
[5/8/2020, 12:26:03 PM] [webostv] webOS - prompt for confirmation                                 
[5/8/2020, 12:26:04 PM] [webostv] webOS - prompt for confirmation                                 
[5/8/2020, 12:26:05 PM] [webostv] webOS - prompt for confirmation                                 
[5/8/2020, 12:26:07 PM] [webostv] webOS - prompt for confirmation                                 
[5/8/2020, 12:26:09 PM] [webostv] webOS - prompt for confirmation                                 
[5/8/2020, 12:26:09 PM] [webostv] webOS - prompt for confirmation                                 
[5/8/2020, 12:26:11 PM] [webostv] webOS - prompt for confirmation                                 
[5/8/2020, 12:26:13 PM] [webostv] webOS - prompt for confirmation                                 
[5/8/2020, 12:26:49 PM] [webostv] webOS - Error: connect EHOSTUNREACH 192.168.1.124:3000          
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {                             
  errno: 'EHOSTUNREACH',                                                                          
  code: 'EHOSTUNREACH',                                                                           
  syscall: 'connect',                                                                             
  address: '192.168.1.124',                                                                       
  port: 3000                                                                                      
}                                                                                                 
                                                                                                 
```
The TV with the IP `192.168.1.124` is the one that fails to response once its been turned on by homekit/homebridge

**Comment by merdok** [comment]
Your tv is not reachable, you either did not allow the connection or you do not have the required options enabled on your tv. Also your Network might be blocking the connection to your tv.

**Comment by gussyboy** [comment]
> Its on the same network
> 
> > The thing I notice is when turning on Mobile TV On it doesn't give me a simple on or off option but instead the option to turn on via Wi-Fi or Bluetooth. Neither of my TV's are connected by Wi-Fi, they're both hardwired via ethernet.
> 
> I think its related to the Mobile TV On feature, which seems to only be Wifi or bluetooth on this model

I mentioned this before, would that be related?

I’m able to turn the tv on via HomeKit and then that websocket issue occurs and it doesn’t response again until homebridge is restarted.

**Comment by merdok** [comment]
I do not think that it makes a difference if it is connected via LAN or WiFi, but to be sure you need to test it. With speculations we will not be able to solve this issue. 

You could also try to ping your tv from another device to see if it responds to make sure that it is reachable under the specified ip. For turning on the  tv a ip is not needed, so that is why you are able to turn the tv on.

**Comment by agneevX** [comment]
Any update on this? Still can't add one of my TVs. This could fix #223.

**Comment by merdok** [comment]
Is your second TV reachable in your network and are you able to ping it?

**Comment by agneevX** [comment]
Yes, I'm able to do that.

**Comment by gussyboy** [comment]
Yes, I'm able to ping both just fine.

Still getting this error in terminal
```
[5/11/2020, 8:04:06 PM] [webostv] webOS - Error: connect ECONNREFUSED 192.168.1.114:3000                                                                                                                          
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {                                                                                                                                             
  errno: 'ECONNREFUSED',                                                                                                                                                                                          
  code: 'ECONNREFUSED',                                                                                                                                                                                           
  syscall: 'connect',                                                                                                                                                                                             
  address: '192.168.1.114',                                                                                                                                                                                       
  port: 3000                                                                                                                                                                                                      
}                                                                                                                                                                                                                 
[5/11/2020, 8:04:27 PM] [webostv] webOS - Error: Sec-WebSocket-Accept header from server didn't match expected value of 7pHzyQcr89yNc0kf0/s/UfsEufg=                                                              
    at WebSocketClient.failHandshake (/usr/local/lib/node_modules/homebridge-webos-tv/node_modules/websocket/lib/WebSocketClient.js:339:32)                                                                       
    at WebSocketClient.validateHandshake (/usr/local/lib/node_modules/homebridge-webos-tv/node_modules/websocket/lib/WebSocketClient.js:326:14)                                                                   
    at ClientRequest.handleRequestUpgrade (/usr/local/lib/node_modules/homebridge-webos-tv/node_modules/websocket/lib/WebSocketClient.js:261:14)                                                                  
    at ClientRequest.emit (events.js:310:20)                                                                                                                                                                      
    at Socket.socketOnData (_http_client.js:503:11)                                                                                                                                                               
    at Socket.emit (events.js:310:20)                                                                                                                                                                             
    at addChunk (_stream_readable.js:286:12)                                                                                                                                                                      
    at readableAddChunk (_stream_readable.js:268:9)                                                                                                                                                               
    at Socket.Readable.push (_stream_readable.js:209:10)                                                                                                                                                          
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)                                                                                                                                                  
[5/11/2020, 8:04:27 PM] [webostv] webOS - prompt for confirmation   ```

**Comment by merdok** [comment]
@gussyboy 
I see ` [5/11/2020, 8:04:27 PM] [webostv] webOS - prompt for confirmation  ` in your log. Did you accept the connection on the tv? 

@gussyboy @agneevX maybe you both just did not allow connection on your second TV or maybe the "Mobile TV On" feature is not enabled?

**Comment by gussyboy** [comment]
> I didn't get asked to allow connection to the tv either, which is clearly a issue

I never got asked and I’m not sure how to force it to ask again

**Comment by merdok** [comment]
If you did not get asked and you are sure that your TV is reachable then i guess you just did not enable all the required settings on your TV.

**Comment by merdok** [comment]
Closing due to inactivity.
