### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by netRunner0** [merdok/homebridge-webos-tv#230]
[4/30/2020, 13:03:00] [ТВ Гостиная] webOS - Error: Sec-WebSocket-Accept header from server didn't match expected value of AJ2knN/iwkcbMiGSujR7QrmA78Q=
    at WebSocketClient.failHandshake (/usr/lib/node_modules/homebridge-webos-tv/node_modules/websocket/lib/WebSocketClient.js:339:32)
    at WebSocketClient.validateHandshake (/usr/lib/node_modules/homebridge-webos-tv/node_modules/websocket/lib/WebSocketClient.js:326:14)
    at ClientRequest.handleRequestUpgrade (/usr/lib/node_modules/homebridge-webos-tv/node_modules/websocket/lib/WebSocketClient.js:261:14)
    at ClientRequest.emit (events.js:310:20)
    at Socket.socketOnData (_http_client.js:510:11)
    at Socket.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
    at readableAddChunk (_stream_readable.js:268:9)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
[4/30/2020, 13:03:01] [Yamaha RX-V779] Updating input from Apple TV to Apple TV

**Comment by merdok** [comment]
Sometimes due to error in transmission such error might appear, but this is not an issue and does not negatively affect the plugin.
