### ISSUE TITLE
TypeError: this.config.devices is not iterable

### ISSUE THREAD

**Issue by BarnicleFiend** [merdok/homebridge-webos-tv#239]
Does anyone know what is causing the error below? 

Worked for me previously as an accessory, not having any luck as an accessory or platform now. Could be a basic error.

23/05/2020, 20:36:02 [webostv] webOS - init - initializing devices
23/05/2020, 20:36:02 TypeError: this.config.devices is not iterable
    at webosTvPlatform.initDevices (/home/hoobs/.hoobs/node_modules/homebridge-webos-tv/index.js:1576:44)
    at API.emit (events.js:228:7)
    at Server.run (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:104:18)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:84:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:95:81)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11
23/05/2020, 20:36:02 Got SIGTERM, shutting down Bridge...

**Comment by merdok** [comment]
Would be good if you could post your config here, the error indicates that you have an issue there.

**Comment by BarnicleFiend** [comment]
I'm using HOOBS, config as below:

{
    "platform": "webostv",
    "devices": [
        {
            "name": "LG TV",
            "ip": "XXX",
            "mac": "XXX",
            "pollingInterval": 10,
            "inputs": [
                {
                    "appId": "com.webos.app.livetv",
                    "name": "Live TV"
                },
                {
                    "appId": "com.webos.app.hdmi1",
                    "name": "ChromeCast"
                }
            ]
        }
    ]
}

**Comment by merdok** [comment]
Honestly, no idea what is causing the issue. The config looks good to me. Maybe something with HOOBS?

**Comment by vahov** [comment]
I am on Homebridge 1.1.0 and 1.8.0 caused also the same error and Homebridge crashed:
TypeError: res.channelList is not iterable
    at /usr/local/lib/node_modules/homebridge-webos-tv/index.js:293:49
    at Object.callbacks.<computed> (/usr/local/lib/node_modules/homebridge-webos-tv/node_modules/lgtv2/index.js:216:25)
    at WebSocketConnection.<anonymous> (/usr/local/lib/node_modules/homebridge-webos-tv/node_modules/lgtv2/index.js:146:48)
    at WebSocketConnection.emit (events.js:310:20)
    at WebSocketConnection.processFrame (/usr/local/lib/node_modules/homebridge-webos-tv/node_modules/websocket/lib/WebSocketConnection.js:554:26)
    at /usr/local/lib/node_modules/homebridge-webos-tv/node_modules/websocket/lib/WebSocketConnection.js:323:40
    at processTicksAndRejections (internal/process/task_queues.js:79:11)

Reverted back to 1.7.1 and everything is working again.

**Comment by merdok** [comment]
@vahov your issue has something to do with a new feature which i introduced in the latest update. I will fix that.
But i would still like to know why it does not work on your TV. What TV are you using and what webos version does it have? Did you add your tv as an accessory or platform?

**Comment by vahov** [comment]
The TV is LG B9 and it is added through Config UI as platform. Can not confirm the Webos version at this moment but I think the 2019 ones have 4 or 4.5 or something.

**Comment by merdok** [comment]
Can you please try now with version 1.8.1? Also there should be a debug log now in the console related to the channel list, could you please check if it is there and paste here?

**Comment by vahov** [comment]
It seems that somebody tried already and the bug is still there #242

**Comment by merdok** [comment]
This is again a different issue

**Comment by BarnicleFiend** [comment]
Ok - I've updated to 1.8.1 and the error is gone. Replaced on the log by a single line:

25/05/2020, 10:57:39 [webostv] Init - initializing devices

Config remains the same. TV doesn't appear in 'add accessories' in the home app though for some reason. I've enabled 'LG Connect Apps', my TV doesn't have 'Mobile TV On' under general settings. Its a UK 49" 2016 model with software version 04.26.00.

**Comment by merdok** [comment]
Not sure what is the issue here , config looks ok. I would guess this has something to do with HOOBS. Maybe some outdated libs like nodejs?

**Comment by BarnicleFiend** [comment]
I've just updated Node JS is from v10.15.2 to v10.19.0.

'Nearby accessories' is now appearing in 'Add accessory' for a few seconds with a gap as though something should be there. Nothing showing however, no changes to log or config.

**Comment by merdok** [comment]
Could you try with version 1.8.2?

**Comment by BarnicleFiend** [comment]
Updated to 1.8.2 - another line has appeared on the log:

25/05/2020, 23:47:43 [webostv] Init - initializing devices
25/05/2020, 23:47:43 [webostv] The devices property is not of type array. Cannot initialize. Type: object

**Comment by merdok** [comment]
Yes, and there is your issue. Your `devices` property is not an array, it is an object. `devices` must be an array of your tvs, or else it will not work.

**Comment by BarnicleFiend** [comment]
Thanks for your help working this out. 

I only have one tv, how do I change my ‘devices’ to an array?

**Comment by merdok** [comment]
Your config looks already like an array: [{device config}], so I guess something is maybe changing your config? You could also try adding your tv twice and check if that changes anything.

**Comment by BradJMelb** [comment]
My setup has been running without issue for a long time. I installed the latest release today and I’m getting errors too. I see this when trying to start:
`[5/27/2020, 1:32:37 PM] TypeError: Cannot read property 'user' of undefined                                                 
    at new webosTvDevice (/usr/local/lib/node_modules/homebridge-webos-tv/index.js:49:48)                                   
    at new webosTvAccessory (/usr/local/lib/node_modules/homebridge-webos-tv/index.js:1684:9)                               
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:308:29)                                
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:91:38)                                              
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)                                             
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)                                     
    at Module._compile (internal/modules/cjs/loader.js:689:30)                                                              
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)                                                
    at Module.load (internal/modules/cjs/loader.js:599:32)                                                                  
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)                                                                
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)                                                         
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)                                                      
    at startup (internal/bootstrap/node.js:279:19)                                                                          
    at bootstrapNodeJSCore (internal/bootstrap/node.js:752:3)                                                               
[5/27/2020, 1:32:37 PM] Got SIGTERM, shutting down Homebridge... `

I can update this post with my config file later but I haven’t changed my config since before multiple TV support existed. 

Thanks,
Brad.

**Comment by merdok** [comment]
Could you please post your config? I am wondering why you have no api object? Do you have the latest homebridge installed?

**Comment by BarnicleFiend** [comment]
Hi merdok,

That solved it for me, thanks for your help. It appears it was a HOOBS issue. This is the revised config that now works:

[
    {
        "name": "TV",
        "ip": "192.168.1.102",
        "mac": "E8:F2:E2:4A:89:E4",
        "pollingInterval": 10,
        "inputs": [
            {
                "appId": "com.webos.app.livetv",
                "name": "Live TV"
            },
            {
                "appId": "com.webos.app.hdmi1",
                "name": "ChromeCast"
            }
        ]
    }
]


The previous config I shared was created the error when HOOBS amalgamated it together with the other platform configs. In the config.json it was showing like this, leading to the object error:

 {
            "platform": "webostv",
            "plugin_map": {
                "plugin_name": "homebridge-webos-tv"
            },
            "devices": {
                "platform": "webostv",
                "devices": [
                    {
                        "name": "TV",
                        "ip": "192.168.1.102",
                        "mac": "E8:F2:E2:4A:89:E4",
                        "pollingInterval": 10,
                        "inputs": [
                            {
                                "appId": "com.webos.app.livetv",
                                "name": "Live TV"
                            },
                            {
                                "appId": "com.webos.app.hdmi1",
                                "name": "ChromeCast"
                            }
                        ]
                    }
                ]
            }
        }

I'm unable to turn the TV on using homebridge but I suspect that's because my TV doesn't have the 'Mobile TV On' option. Is there a way round this? (TV turns on fine with google home through chromecast and CEC).

**Comment by merdok** [comment]
@BarnicleFiend thanks for the info! Good that you solved the issue.
If you do not have "Mobile TV On" then you will not be able to turn on the TV. For CEC to work your device which you are running homebridge on would need to be connected to your TV per HDMI to work. But i think a 2016 model should have the functionality to turn it on. I had a UH model a few years ago and it was working. Maybe just on your TV the option is called differently, or your mac address is wrong?
