### ISSUE TITLE
Not Reconized

### ISSUE THREAD

**Issue by djbrendon** [merdok/homebridge-webos-tv#254]
Hey! I just updated the homebridge-webos-tv plugin today and after doing so, I could no longer start the homebridge service. So I removed the plugin fully, which allowed me to start the service and everything to start working. However, after installing the homebridge-webos-tv plugin again, it causes the service to not start. I am using Hoobs to manage my homebridge environment but even tried installing manually. Below is the output of the logs when starting:

`[Homebridge] [6/4/2020, 5:38:07 PM] Loaded config.json with 0 accessories and 3 platforms.[Homebridge] [6/4/2020, 5:38:08 PM] Loaded plugin: "homebridge-smartthings-v2"[Homebridge] [6/4/2020, 5:38:08 PM] Registering platform "homebridge-smartthings-v2.SmartThings-v2"[Homebridge] [6/4/2020, 5:38:08 PM] Error Loading Plugin "homebridge-webos-tv"[Homebridge] [6/4/2020, 5:38:10 PM] Loaded plugin: "ring"[Homebridge] [6/4/2020, 5:38:10 PM] Registering platform "homebridge-ring.Ring"[Homebridge] [6/4/2020, 5:38:10 PM] Loading 3 platforms...[Homebridge] [6/4/2020, 5:38:10 PM] [Ring] Initializing Ring platform...[Homebridge] [6/4/2020, 5:38:10 PM] [SmartThings-v2] Initializing SmartThings-v2 platform...[Homebridge] INFO: Homebridge Version: 2.4[Homebridge] INFO: SmartThings-v2 Plugin Version: 2.3.4[Homebridge] INFO: Checking Package Version for Updates...[Homebridge] [6/4/2020, 5:38:10 PM] Error: The requested platform 'webostv' was not registered by any plugin.
    at API.platform (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/api.js:115:19)
    at Server._loadPlatforms (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:283:47)
    at Server.run (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:74:14)
    at module.exports (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/cli.js:90:12)
    at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/bin/homebridge:10:63)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)[Homebridge] ERROR: uncaughtException: The requested platform 'webostv' was not registered by any plugin.[Homebridge] Error: The requested platform 'webostv' was not registered by any plugin.[Homebridge] at API.platform (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/api.js:115:19)[Homebridge] at Server._loadPlatforms (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:283:47)[Homebridge] at Server.run (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:74:14)[Homebridge] at module.exports (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/cli.js:90:12)[Homebridge] at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/bin/homebridge:10:63)[Homebridge] at Module._compile (internal/modules/cjs/loader.js:778:30)[Homebridge] at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)[Homebridge] at Module.load (internal/modules/cjs/loader.js:653:32)[Homebridge] at tryModuleLoad (internal/modules/cjs/loader.js:593:12)[Homebridge] at Function.Module._load (internal/modules/cjs/loader.js:585:3)`

Any ideas of what to check exactly?

**Comment by merdok** [comment]
It can be that you have outdated dependencies. Like node or homebridge. Please try to update them.

**Comment by djbrendon** [comment]
Thank you! I should have checked that before. I did find Node was outdated as well as the homebridge. Updated and now can install the plugin without it crashing. Now just trying to get it configured. For some reason, before the update, Hoobs separated out each setting but now it is only allowing me to manually enter everything. Closing.
