### ISSUE TITLE
Error Causes Homebridge Service to Crash

### ISSUE THREAD

**Issue by mlaine2013** [merdok/homebridge-webos-tv#273]
8/1/2020, 3:25:43 PM [webostv] [Living Room TV] App launched, current appId: com.webos.app.hdmi1
8/1/2020, 3:30:48 PM [webostv] [Living Room TV] Disconnected from TV
8/1/2020, 3:30:52 PM [webostv] [Living Room TV] Connected to TV
8/1/2020, 3:30:52 PM [webostv] [Living Room TV] Connected to TV
8/1/2020, 3:31:02 PM ReferenceError: error is not defined
    at /home/hoobs/.hoobs/node_modules/homebridge-webos-tv/index.js:200:59
    at /home/hoobs/.hoobs/node_modules/lgtv2/index.js:251:17
    at Timeout._onTimeout (/home/hoobs/.hoobs/node_modules/lgtv2/index.js:222:29)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
8/1/2020, 3:31:02 PM [webostv] [Living Room TV] Current app - error while getting current app info
8/1/2020, 3:31:02 PM [webostv] [Living Room TV] Error: Error: timeout
    at Timeout._onTimeout (/home/hoobs/.hoobs/node_modules/lgtv2/index.js:222:32)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
8/1/2020, 3:31:02 PM Got SIGTERM, shutting down Bridge...
8/1/2020, 3:31:02 PM ReferenceError: error is not defined
    at /home/hoobs/.hoobs/node_modules/homebridge-webos-tv/index.js:200:59
    at /home/hoobs/.hoobs/node_modules/lgtv2/index.js:251:17
    at Timeout._onTimeout (/home/hoobs/.hoobs/node_modules/lgtv2/index.js:222:29)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
8/1/2020, 3:31:02 PM [webostv] [Living Room TV] Current app - error while getting current app info
8/1/2020, 3:31:02 PM [webostv] [Living Room TV] Error: Error: timeout
    at Timeout._onTimeout (/home/hoobs/.hoobs/node_modules/lgtv2/index.js:222:32)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)

**Comment by merdok** [comment]
Thanks for letting me know. The crash should be fixed in version 1.9.3
