### ISSUE TITLE
webos was not registered by any plugin

### ISSUE THREAD

**Issue by KeshavMadhavan** [merdok/homebridge-webos-tv#293]
[9/15/2020, 11:04:47 AM] Error loading accessory requested in your config.json at position 1
[9/15/2020, 11:04:48 AM] Error: The requested accessory 'webostv' was not registered by any plugin.
    at PluginManager.getPluginForAccessory (/usr/local/lib/node_modules/homebridge/src/pluginManager.ts:198:15)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:345:37
    at Array.forEach (<anonymous>)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/src/server.ts:328:29)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:154:12)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1076:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:941:32)
pi@pi:~ $ 

This is the error I'm getting. Not sure how to fix it

**Comment by merdok** [comment]
You most probably do not have the plugin installed?
