### ISSUE TITLE
Homebridge crash on getCharacteristics

### ISSUE THREAD

**Issue by mrNakamura** [merdok/homebridge-webos-tv#299]
Hi Folks,

Got this exception when moving TV items around on the accessories page of home bridge.
UPDATE: Actually seems to happen when you push the TV Volume button to mute/unmute..
Thought it was worthy of a quick bug report.

Ta

[9/22/2020, 09:48:13] TypeError: Cannot read property 'getCharacteristic' of undefined
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-webos-tv/index.js:919:28)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
[9/22/2020, 09:48:13] Got SIGTERM, shutting down Homebridge...
[9/22/2020, 09:48:13] [Config] Failed to get characteristics for LG TV Volume with iid 18: socket hang up
[9/22/2020, 09:48:18] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null

**Comment by merdok** [comment]
Hi,
thanks for the report. Could you please describe more detailed how to exactly reproduce the issue?

**Comment by mrNakamura** [comment]
Sure, on the homebridge Accessories, click the "LG TV Volume" button as if to mute/unmute..

Screenshot here.
Exceptions every time (TV's off at the moment, but doesn't make much difference I think)..


![2020-09-22 18 49 19](https://user-images.githubusercontent.com/57640903/93918725-a64d4600-fd04-11ea-8edf-4d34f7c5f1ec.png)

**Comment by mrNakamura** [comment]
actually might only be when the TV is off, but will confirm later..

**Comment by grzegorz914** [comment]
I can confirm this too, if TV is OFF and we press the volume Tile then the homebridge crashes with error reported @mrNakamura

**Comment by merdok** [comment]
Thanks! Will check it out!

**Comment by merdok** [comment]
Should be fixed in version 2.0.4. Could you try it and please let me know.

**Comment by grzegorz914** [comment]
Yes, the error is fixed now.

**Comment by mrNakamura** [comment]
Yes, fixed for me too.  Many thanks 😊
