### ISSUE TITLE
Crashing Homebridge After Update

### ISSUE THREAD

**Issue by bwalls** [merdok/homebridge-webos-tv#302]
Started getting the following after most recent update.

 [webostv] Init - initializing devices
[9/24/2020, 16:31:59] [webostv] [LG OLED tv] Init - got TV configuration, initializing device with name: LG OLED tv
[9/24/2020, 16:31:59] Error: Cannot add more than 100 services to a single accessory!
    at Accessory._this.addService (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:289:13)
    at PlatformAccessory.addService (/usr/local/lib/node_modules/homebridge/src/platformAccessory.ts:93:41)
    at /usr/local/lib/node_modules/homebridge-webos-tv/index.js:769:23
    at Array.forEach (<anonymous>)
    at webosTvDevice.prepareRemoteControlButtonService (/usr/local/lib/node_modules/homebridge-webos-tv/index.js:744:31)
    at webosTvDevice.setupAccessoryServices (/usr/local/lib/node_modules/homebridge-webos-tv/index.js:229:10)
    at webosTvDevice.initTvAccessory (/usr/local/lib/node_modules/homebridge-webos-tv/index.js:205:10)
    at new webosTvDevice (/usr/local/lib/node_modules/homebridge-webos-tv/index.js:122:10)
    at webosTvPlatform.initDevices (/usr/local/lib/node_modules/homebridge-webos-tv/index.js:1819:11)
    at HomebridgeAPI.emit (events.js:322:22)
    at HomebridgeAPI.signalFinished (/usr/local/lib/node_modules/homebridge/src/api.ts:251:10)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:158:14)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)

**Comment by bwalls** [comment]
The problem seems to be with including the following in configs:
,
                    "remoteControlButtons": [
                        "HOME",
                        "LIST",
                        "EXIT",
                        "AD",
                        "DASH",
                        "MUTE",
                        "VOLUMEUP",
                        "VOLUMEDOWN",
                        "CHANNELUP",
                        "CHANNELDOWN",
                        "MENU",
                        "UP",
                        "DOWN",
                        "LEFT",
                        "RIGHT",
                        "CLICK",
                        "BACK",
                        "EXIT",
                        "PROGRAM",
                        "ENTER",
                        "RED",
                        "GREEN",
                        "YELLOW",
                        "BLUE",
                        "LIVE_ZOOM",
                        "CC"
                    ],

**Comment by merdok** [comment]
There is a limit of 100 services per accessory for HomeKit devices. There is unfortunately nothing i can do about it. You have to remove some of the buttons. Another option would be that you create a second TV (same ip and mac, different name) and split your controls across those two TVs.

**Comment by bwalls** [comment]
Any idea what changed? Were some hidden or default services added in the update?

**Comment by merdok** [comment]
Yes, there are now some additional default services which were not there before.

**Comment by bwalls** [comment]
Okay, makes sense, thanks.

I very much appreciate the work you 've done on this plugin. Thank you!
