### ISSUE TITLE
Strange Error in Homebridge Log: 'Does not look like a valid storage file!'

### ISSUE THREAD

**Issue by crazylenni** [merdok/homebridge-webos-tv#315]
Hi,
i just got this nice plugin running, but i got the following message in my log:

`(node:1833) UnhandledPromiseRejectionWarning: Error: [node-persist][readFile] /homebridge/persist/AccessoryInfo.0E5E6F2BF4D1.json does not look like a valid storage file!
    at /homebridge/node_modules/homebridge-yamaha-avr/node_modules/node-persist/src/local-storage.js:314:89
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
(node:1833) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)`

I tried to set the key file location and prefs directoy both to `/homebridge/persist`. This is not changing anything.
Is there a way to prevent this error?

Thanks!

PS: I'm running homebridge inside a docker container on the synology DS716+II

**Comment by merdok** [comment]
Hi,
this error does not look like anything related to this plugin. This looks more like an issue with your homebridge or nodejs installation. Maybe try to do a clean install of those and double check your permissions.

**Comment by crazylenni** [comment]
I'm sorry. I assigned this bug to the right plug-in repo.
