### ISSUE TITLE
LOG Error: get current Channel and Name error: Error: timeout

### ISSUE THREAD

**Issue by andjandre** [merdok/homebridge-webos-tv#325]
Hey Together,

my log is spammed with following error. 

I hava a LG OLED55CX. I'am using HOOBS. The Homekit integration works fine but I would like to get rid of these Errors. 

```LOG
25.11.2020, 09:43:20 [LgWebOsTv] Device: 192.168.178.140 LG TV Channels, get current Channel and Name error: Error: timeout
    at Timeout._onTimeout (/home/hoobs/.hoobs/node_modules/lgtv2/index.js:228:32)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7).
```

```JSON
{
            "platform": "LgWebOsTv",
            "plugin_map": {
                "plugin_name": "homebridge-lgwebos-tv"
            },
            "devices": [
                {
                    "name": "LG TV Channels",
                    "host": "192.168.178.140",
                    "mac": "58:FD:B1:7F:D6:90",
                    "switchInfoMenu": false,
                    "inputs": [
                        {
                            "name": "YouTube",
                            "reference": "youtube.leanback.v4",
                            "type": "APPLICATION",
                            "mode": 0
                        },
                        {
                            "name": "XBox",
                            "reference": "com.webos.app.hdmi1",
                            "type": "HDMI",
                            "mode": 0
                        },
                        {
                            "name": "Disney Plus",
                            "reference": "com.disney.disneyplus-prod",
                            "type": "TUNER",
                            "mode": 0
                        },
                        {
                            "name": "HDMI 2",
                            "reference": "com.webos.app.hdmi2",
                            "type": "HDMI",
                            "mode": 0
                        },
                        {
                            "name": "Netflix",
                            "reference": "netflix",
                            "type": "APPLICATION",
                            "mode": 0
                        },
                        {
                            "name": "Amazon Prime",
                            "reference": "amazon",
                            "type": "APPLICATION",
                            "mode": 0
                        },
                        {
                            "name": "Apple TV",
                            "reference": "com.apple.appletv",
                            "type": "APPLICATION",
                            "mode": 0
                        }
                    ],
                    "manufacturer": "Manufacturer",
                    "modelName": "Model",
                    "serialNumber": "58:fd:b1:7f:d6:90",
                    "firmwareRevision": "11.25"
                }
            ]
        },
```

**Comment by merdok** [comment]
Hi, 
you are using the other plugin which is a rip off of this one.
You should switch to this plugin or open the issue on the other repo.

**Comment by andjandre** [comment]
Thank you very much. Switched to your version and no more problems what so ever. Amazing how fast you responded and how well this implementation works
