### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: Promise.allSettled is not a function

### ISSUE THREAD

**Issue by krasnyt** [merdok/homebridge-webos-tv#345]
Hello, I just faced an issue shown below right after installing the plugin and restarting homebridge. 

Nodejs: 10.23.1
npm: 7.5.3
TV: LG OLED65B9, webOS v05.00.15

Any idea on a possible fix? Thx.

> [2/12/2021, 10:29:43 PM] [webostv] [LG OLEDDDD] Connected to TV
(node:6812) UnhandledPromiseRejectionWarning: TypeError: Promise.allSettled is not a function
    at LgTvController.getTvInformation (/usr/local/lib/node_modules/homebridge-webos-tv/lib/LgTvController.js:267:19)
    at LgTvController.setupTvConnection (/usr/local/lib/node_modules/homebridge-webos-tv/lib/LgTvController.js:194:10)
    at LGTV.lgtv.on (/usr/local/lib/node_modules/homebridge-webos-tv/lib/LgTvController.js:159:14)
    at LGTV.emit (events.js:198:13)
    at Object.36fe74230000 (/usr/local/lib/node_modules/homebridge-webos-tv/node_modules/lgtv2/index.js:169:26)
    at WebSocketConnection.<anonymous> (/usr/local/lib/node_modules/homebridge-webos-tv/node_modules/lgtv2/index.js:149:48)
    at WebSocketConnection.emit (events.js:198:13)
    at WebSocketConnection.processFrame (/usr/local/lib/node_modules/homebridge-webos-tv/node_modules/websocket/lib/WebSocketConnection.js:554:26)
    at /usr/local/lib/node_modules/homebridge-webos-tv/node_modules/websocket/lib/WebSocketConnection.js:323:40
    at process._tickCallback (internal/process/next_tick.js:61:11)
(node:6812) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:6812) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by krasnyt** [comment]
Migrating to newer nodejs solved it, closing.
