### ISSUE TITLE
Issue when putting my Mac address

### ISSUE THREAD

**Issue by EricWander** [merdok/homebridge-webos-tv#368]
Hi all,

I have an invalid arg with my Mac address and I don't know why ?
[4/30/2021, 6:56:28 AM] [webostv] Init - initializing devices
[4/30/2021, 6:56:28 AM] [webostv] [LGtv] Init - got TV configuration, initializing device with name: LGtv
[4/30/2021, 6:56:28 AM] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:120:11)
    at join (path.js:1039:7)
    at module.exports (/usr/lib/node_modules/homebridge-webos-tv/node_modules/persist-path/index.js:19:22)
    at new LGTV (/usr/lib/node_modules/homebridge-webos-tv/node_modules/lgtv2/index.js:48:16)
    at LgTvController.setupLgtvInstance (/usr/lib/node_modules/homebridge-webos-tv/lib/LgTvController.js:147:17)
    at LgTvController.connect (/usr/lib/node_modules/homebridge-webos-tv/lib/LgTvController.js:124:14)
    at webosTvDevice.connectToTv (/usr/lib/node_modules/homebridge-webos-tv/index.js:139:19)
    at new webosTvDevice (/usr/lib/node_modules/homebridge-webos-tv/index.js:125:10)
    at webosTvPlatform.initDevices (/usr/lib/node_modules/homebridge-webos-tv/index.js:1831:11)
    at HomebridgeAPI.emit (events.js:326:22)

My json script :
{
    "platform": "webostv",
    "devices": [
        {
            "name": "LGtv",
            "ip": "192.168.0.22",
            "mac": "0c:8e:29:e6:3b:ba"
        }
    ]
}

Thanks for your help

Eric

**Comment by merdok** [comment]
I think something is wrong with your homebridge installation. Please reinstall homebridge and the plugin and make sure all are up to date.

**Comment by EricWander** [comment]
Thanks for your prompt feedback. Did the updates to the latests versions and updated as well the dependencies but still have the same issue. If I remove the Mac address the script is working but it is saying that Mac address is mandatory for this plugin....As soon I add the Mac address I have this INVALID_ARG_TYPE error

Thanks for your help

**Comment by merdok** [comment]
Maybe your config.json is broken. The error does not come from the "mac" according to the log you provided above, but from an internal homebridge variable called "path". It might be that your config.json is wrongly formatted and therefore is also wrongly parsed.

**Comment by EricWander** [comment]
Indeed, I'm using Homebridge as a plugin on a Jeedom Server. Could be this the issue ? Where can I find the Config.json file on the setup ? 
Thanks

**Comment by merdok** [comment]
It is usually located in the .homebridge directory which is located in user home directory.

**Comment by EricWander** [comment]
Here is my config.json file. There is a path keyword but I don't understand why it is working when I put only the ip address and not the Mac adresse in my WebOs plugin ? Really strange. Any idea ?
[config.txt](https://github.com/merdok/homebridge-webos-tv/files/6425375/config.txt)

**Comment by merdok** [comment]
All look good to me, not sure what the issue is. I suspect that something is wrong with your homebridge installation, maybe permissions? You would need to investigate that.

**Comment by EricWander** [comment]
Still stuck with this issue :( . I gave the full permission to the Homebridge plugin but still the same issue. Any other idea ? 

Thanks
