### ISSUE TITLE
v2.2.3 crashing Homebridge and causing service restart loop

### ISSUE THREAD

**Issue by idealdreams** [merdok/homebridge-webos-tv#392]
I updated to version 2.2.3 this evening. I noticed if I interact with my TVs in the Home app, it sends my Homebridge service into a restart loop. Each time the loop cycles, my LG TV asks me if I want to accept the pairing request for the LG Connect app. When I click yes, nothing happens on the TV and then the Homebridge service restarts. 

I had to uninstall the plugin to stabilize Homebridge. This plugin has worked seamlessly for me for the better part of two years now so I'm not sure what changed. All configurations on my end remain the same.

**Comment by calvinyeap** [comment]
I'm having the same issue too and reverting back to v2.2.2 didn't solve the problem either. Weirdly enough, everything loads just fine if my TV is switched off. When I turn it on, it will caught in the following loop.

[30/09/2021, 12:22:10] Homebridge v1.3.4 (homebridge-webos-tv) is running on port 59611.
Preparing Advertiser for 'LG TV C0D3' using bonjour-hap backend!
Starting to advertise 'LG TV C0D3' using bonjour-hap backend!
[30/09/2021, 12:22:10] LG TV C0D3 is running on port 41449.
[30/09/2021, 12:22:10] Please add [LG TV C0D3] manually in Home app. Setup Code: 314-94-553
[30/09/2021, 12:23:04] [homebridge-webos-tv] [LG TV] Connected to TV
[30/09/2021, 12:23:04] [homebridge-webos-tv] Child bridge process ended
[30/09/2021, 12:23:04] [homebridge-webos-tv] Process Ended. Code: null, Signal: SIGBUS
[30/09/2021, 12:23:11] [homebridge-webos-tv] Restarting Process...
Initializing HAP-NodeJS v0.9.4...
[30/09/2021, 12:23:13] [homebridge-webos-tv] Launched child bridge with PID 1723
[30/09/2021, 12:23:13] Registering platform 'homebridge-webos-tv.webostv'
[30/09/2021, 12:23:13] [homebridge-webos-tv] Loaded homebridge-webos-tv v2.2.3 child bridge successfully
[30/09/2021, 12:23:14] Loaded 0 cached accessories from cachedAccessories.0EFDA1BF55FD.
Preparing Advertiser for 'homebridge-webos-tv 5ED5' using bonjour-hap backend!
[30/09/2021, 12:23:14] [homebridge-webos-tv] Init - initializing devices
[30/09/2021, 12:23:14] [homebridge-webos-tv] [LG TV] Init - got TV configuration, initializing device with name: LG TV
Starting to advertise 'homebridge-webos-tv 5ED5' using bonjour-hap backend!
[30/09/2021, 12:23:14] Homebridge v1.3.4 (homebridge-webos-tv) is running on port 59611.
Preparing Advertiser for 'LG TV C0D3' using bonjour-hap backend!
Starting to advertise 'LG TV C0D3' using bonjour-hap backend!
[30/09/2021, 12:23:14] LG TV C0D3 is running on port 43807.
[30/09/2021, 12:23:14] Please add [LG TV C0D3] manually in Home app. Setup Code: 314-94-553
[30/09/2021, 12:23:14] [homebridge-webos-tv] [LG TV] Connected to TV
[30/09/2021, 12:23:14] [homebridge-webos-tv] Child bridge process ended
[30/09/2021, 12:23:14] [homebridge-webos-tv] Process Ended. Code: null, Signal: SIGBUS
[30/09/2021, 12:23:21] [homebridge-webos-tv] Restarting Process...
Initializing HAP-NodeJS v0.9.4...
[30/09/2021, 12:23:43] [homebridge-webos-tv] Process Ended. Code: null, Signal: SIGBUS

**Comment by merdok** [comment]
That is strange. The changes in the latest version are certainly not causing the issue.

I suspect that during the update maybe also some dependencies did update and one of them is now causing the issue. That is why @calvinyeap even a revert does not fix it anymore for you.

I would not to have some detailed log, ideally with a call stack for the error or crash. Right now I only see that homebridge did restart from your logs but that does not help me in any way...

**Comment by calvinyeap** [comment]
Sure, can you guide me how to pull that for you?

**Comment by merdok** [comment]
I think you should try to start homebridge in debug mode and see if additional stuff comes up, also I see that you are running child bridge, so not sure if that affects the output log...

**Comment by calvinyeap** [comment]
That's right. I tried to disable as a child device earlier and when I do, my entire homebridge is be on a restart loop. When I enabled back as child device, my homebridge is running fine. In fact, the webos child device is also running until I switch on my TV, then it gets into a restart loop. Here's the log file and at 30/09/2021, 16:03:25 is was me using my phone to turn on the TV which works by the way, but then the TV control becomes unresponsive as the child devices keeps restarting on a loop thereafter.

[30/09/2021, 16:03:09] [homebridge-webos-tv] [LG TV] Connecting to TV
[30/09/2021, 16:03:17] [homebridge-webos-tv] [LG TV] Connecting to TV
[30/09/2021, 16:03:25] [homebridge-webos-tv] [LG TV] Connecting to TV
[30/09/2021, 16:03:25] [homebridge-webos-tv] [LG TV] Wake on LAN callback - sent magic packet, trying to connect to tv...
[30/09/2021, 16:03:25] [homebridge-webos-tv] [LG TV] Trying to wake up TV! Mac: C8-08-E9-CB-5D-98, BroadcastAdr: 255.255.255.255
[30/09/2021, 16:03:25] [homebridge-webos-tv] [LG TV] Connecting to TV
[30/09/2021, 16:03:33] [homebridge-webos-tv] [LG TV] Connecting to TV
[30/09/2021, 16:03:33] [homebridge-webos-tv] [LG TV] Connecting to TV
[30/09/2021, 16:03:35] [homebridge-webos-tv] [LG TV] Error - Error: connect ECONNREFUSED 192.168.68.210:3000
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.68.210',
  port: 3000
}
[30/09/2021, 16:03:40] [homebridge-webos-tv] [LG TV] Connecting to TV
[30/09/2021, 16:03:40] [homebridge-webos-tv] [LG TV] Connecting to TV
[30/09/2021, 16:03:45] [homebridge-webos-tv] [LG TV] Connecting to TV
[30/09/2021, 16:03:45] [homebridge-webos-tv] [LG TV] Connecting to TV
[30/09/2021, 16:03:50] [homebridge-webos-tv] [LG TV] Connecting to TV
[30/09/2021, 16:03:50] [homebridge-webos-tv] [LG TV] Connecting to TV
[30/09/2021, 16:03:55] [homebridge-webos-tv] [LG TV] Connecting to TV
[30/09/2021, 16:03:55] [homebridge-webos-tv] [LG TV] Connecting to TV
[30/09/2021, 16:04:00] [homebridge-webos-tv] [LG TV] Connecting to TV
[30/09/2021, 16:04:00] [homebridge-webos-tv] [LG TV] Connecting to TV
[30/09/2021, 16:04:00] [homebridge-webos-tv] [LG TV] Error - Error: Sec-WebSocket-Accept header from server didn't match expected value of OjqQoIAS/FfQXENsiOtmNH9K5YI=
    at WebSocketClient.failHandshake (/usr/local/lib/node_modules/homebridge-webos-tv/node_modules/websocket/lib/WebSocketClient.js:339:32)
    at WebSocketClient.validateHandshake (/usr/local/lib/node_modules/homebridge-webos-tv/node_modules/websocket/lib/WebSocketClient.js:326:14)
    at ClientRequest.handleRequestUpgrade (/usr/local/lib/node_modules/homebridge-webos-tv/node_modules/websocket/lib/WebSocketClient.js:261:14)
    at ClientRequest.emit (events.js:400:28)
    at Socket.socketOnData (_http_client.js:553:11)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
    at Socket.Readable.push (internal/streams/readable.js:204:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
[30/09/2021, 16:04:00] [homebridge-webos-tv] [LG TV] Message from TV 

[30/09/2021, 16:04:00] [homebridge-webos-tv] [LG TV]  {
  type: 'utf8',
  utf8Data: '{"type":"registered","id":"e892ef0e0000","payload":{"client-key":"bf631c7ffdfe30012d2ccea136e1f102"}}'
}
[30/09/2021, 16:04:00] [homebridge-webos-tv] [LG TV] Connected to TV
[30/09/2021, 16:04:00] [homebridge-webos-tv] [LG TV] Requesting TV information
[30/09/2021, 16:04:00] [homebridge-webos-tv] [LG TV] system service - getSystemInfo requested. 
[30/09/2021, 16:04:00] [homebridge-webos-tv] Child bridge process ended
[30/09/2021, 16:04:00] [homebridge-webos-tv] Process Ended. Code: null, Signal: SIGBUS
[30/09/2021, 16:04:02] [Broadlink RM] **Fakegato-timer: addData  Master Bedroom Aircon { time: 1632989042, temp: 29.1 }  immediate:  false
[30/09/2021, 16:04:07] [homebridge-webos-tv] Restarting Process...
Initializing HAP-NodeJS v0.9.4...
[30/09/2021, 16:04:09] [homebridge-webos-tv] Launched child bridge with PID 515
[30/09/2021, 16:04:09] Registering platform 'homebridge-webos-tv.webostv'
[30/09/2021, 16:04:10] [homebridge-webos-tv] Loaded homebridge-webos-tv v2.2.3 child bridge successfully
[30/09/2021, 16:04:10] Loaded 0 cached accessories from cachedAccessories.0EFDA1BF55FD.
Preparing Advertiser for 'homebridge-webos-tv 5ED5' using bonjour-hap backend!
[30/09/2021, 16:04:10] [homebridge-webos-tv] Init - initializing devices
[30/09/2021, 16:04:10] [homebridge-webos-tv] [LG TV] Init - got TV configuration, initializing device with name: LG TV
[30/09/2021, 16:04:10] [homebridge-webos-tv] [LG TV] Adding 17 new input sources!
[30/09/2021, 16:04:10] [homebridge-webos-tv] [LG TV] Created new input source: appId: com.webos.app.hdmi1, name: Apple TV
[30/09/2021, 16:04:10] [homebridge-webos-tv] [LG TV] Created new input source: appId: com.webos.app.hdmi3, name: Astro NJOI
[30/09/2021, 16:04:10] [homebridge-webos-tv] [LG TV] Created new input source: appId: com.webos.app.camera, name: Camera
[30/09/2021, 16:04:10] [homebridge-webos-tv] [LG TV] Created new input source: appId: com.webos.app.connectionwizard, name: Device Connector
[30/09/2021, 16:04:10] [homebridge-webos-tv] [LG TV] Created new input source: appId: com.webos.app.discovery, name: LG Content Store
[30/09/2021, 16:04:10] [homebridge-webos-tv] [LG TV] Created new input source: appId: com.webos.app.capturetv, name: LG Photo Editor
[30/09/2021, 16:04:10] [homebridge-webos-tv] [LG TV] Created new input source: appId: com.webos.app.livetv, name: Live TV
[30/09/2021, 16:04:10] [homebridge-webos-tv] [LG TV] Created new input source: appId: com.webos.app.notificationcenter, name: Notifications
[30/09/2021, 16:04:10] [homebridge-webos-tv] [LG TV] Created new input source: appId: com.webos.app.scheduler, name: Scheduler
[30/09/2021, 16:04:10] [homebridge-webos-tv] [LG TV] Created new input source: appId: com.webos.app.miracast, name: Screen Share
[30/09/2021, 16:04:10] [homebridge-webos-tv] [LG TV] Created new input source: appId: com.webos.app.smartshare, name: SmartShare
[30/09/2021, 16:04:10] [homebridge-webos-tv] [LG TV] Created new input source: appId: com.webos.app.tvguide, name: TV Guide
[30/09/2021, 16:04:10] [homebridge-webos-tv] [LG TV] Created new input source: appId: com.webos.app.hdmi2, name: Unifi TV
[30/09/2021, 16:04:10] [homebridge-webos-tv] [LG TV] Created new input source: appId: com.webos.app.tvuserguide, name: User Guide
[30/09/2021, 16:04:10] [homebridge-webos-tv] [LG TV] Created new input source: appId: com.webos.app.browser, name: Web Browser
[30/09/2021, 16:04:10] [homebridge-webos-tv] [LG TV] Created new input source: appId: com.webos.app.externalinput.av1, name: AV
[30/09/2021, 16:04:10] [homebridge-webos-tv] [LG TV] Created new input source: appId: com.webos.app.externalinput.component, name: Component
Starting to advertise 'homebridge-webos-tv 5ED5' using bonjour-hap backend!
[30/09/2021, 16:04:10] Homebridge v1.3.4 (homebridge-webos-tv) is running on port 59611.
[30/09/2021, 16:04:10] [homebridge-webos-tv] [LG TV] Connecting to TV
Preparing Advertiser for 'LG TV C0D3' using bonjour-hap backend!
Starting to advertise 'LG TV C0D3' using bonjour-hap backend!
[30/09/2021, 16:04:10] LG TV C0D3 is running on port 34131.
[30/09/2021, 16:04:10] Please add [LG TV C0D3] manually in Home app. Setup Code: 314-94-553
[30/09/2021, 16:04:10] [homebridge-webos-tv] [LG TV] Message from TV 

[30/09/2021, 16:04:10] [homebridge-webos-tv] [LG TV]  {
  type: 'utf8',
  utf8Data: '{"type":"registered","id":"8f458f440000","payload":{"client-key":"bf631c7ffdfe30012d2ccea136e1f102"}}'
}
[30/09/2021, 16:04:10] [homebridge-webos-tv] [LG TV] Connected to TV
[30/09/2021, 16:04:10] [homebridge-webos-tv] [LG TV] Requesting TV information
[30/09/2021, 16:04:10] [homebridge-webos-tv] [LG TV] system service - getSystemInfo requested. 
[30/09/2021, 16:04:10] [homebridge-webos-tv] Child bridge process ended

**Comment by merdok** [comment]
This is highly strange... it just says that child bridge is being restarted but does not actually say why... without a clear indication where the issue originated from it will be hard to fix especially since I cannot reproduce this with my tv.

Could you please dig through some homebridge logs and find if there is somewhere an error?

**Comment by OrigSorceror** [comment]
same happening with me. initially thought my homebridge install was corrupted (as i lost controll of all my C-Bus devices) I was on HOOBs, which had other issues as well with the Ring plugin, so i decided to do a full fresh rebuild using raspberry Pi OS (lite with desktop)  and as soon as i install the webos plugin it asks for pairing when click ok homebridge reports tv connected then reboots and i get the pairing request installed. 

uninstalling the plugin for now as i need to get the rest of the plugins up and running so i can get voice control of my home again.

**Comment by calvinyeap** [comment]
This is the full log, when my TV is switched off, the child device seems to be running and log shows "Connecting to TV" all the time. When I finall press to turn on the TV using my phone, the TV switches on and then the following error occurs.

[30/09/2021, 17:06:49] [homebridge-webos-tv] [LG TV] Connecting to TV
[30/09/2021, 17:06:56] [homebridge-webos-tv] [LG TV] Wake on LAN callback - sent magic packet, trying to connect to tv...
[30/09/2021, 17:06:56] [homebridge-webos-tv] [LG TV] Trying to wake up TV! Mac: C8-08-E9-CB-5D-98, BroadcastAdr: 255.255.255.255
[30/09/2021, 17:06:56] [homebridge-webos-tv] [LG TV] Connecting to TV
[30/09/2021, 17:06:58] [homebridge-webos-tv] [LG TV] Connecting to TV
[30/09/2021, 17:07:01] [homebridge-webos-tv] [LG TV] Connecting to TV
[30/09/2021, 17:07:06] [homebridge-webos-tv] [LG TV] Connecting to TV
[30/09/2021, 17:07:06] [homebridge-webos-tv] [LG TV] Connecting to TV
[30/09/2021, 17:07:06] [homebridge-webos-tv] [LG TV] Error - Error: connect ECONNREFUSED 192.168.68.210:3000
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.68.210',
  port: 3000
}
[30/09/2021, 17:07:11] [homebridge-webos-tv] [LG TV] Connecting to TV
[30/09/2021, 17:07:11] [homebridge-webos-tv] [LG TV] Connecting to TV
[30/09/2021, 17:07:12] [Broadlink RM] **Fakegato-timer: addData  Master Bedroom Aircon { time: 1632992832, temp: 29.2 }  immediate:  false
[30/09/2021, 17:07:16] [homebridge-webos-tv] [LG TV] Connecting to TV
[30/09/2021, 17:07:16] [homebridge-webos-tv] [LG TV] Connecting to TV
[30/09/2021, 17:07:21] [homebridge-webos-tv] [LG TV] Connecting to TV
[30/09/2021, 17:07:21] [homebridge-webos-tv] [LG TV] Connecting to TV
[30/09/2021, 17:07:22] [Broadlink RM] **Fakegato-timer: addData  Master Bedroom Aircon { time: 1632992842, temp: 29.3 }  immediate:  false
[30/09/2021, 17:07:26] [homebridge-webos-tv] [LG TV] Connecting to TV
[30/09/2021, 17:07:26] [homebridge-webos-tv] [LG TV] Connecting to TV
[30/09/2021, 17:07:31] [homebridge-webos-tv] [LG TV] Connecting to TV
[30/09/2021, 17:07:31] [homebridge-webos-tv] [LG TV] Connecting to TV
[30/09/2021, 17:07:31] [homebridge-webos-tv] [LG TV] Error - Error: Sec-WebSocket-Accept header from server didn't match expected value of gQLTKtNZnN4bPsR0+YqPwOFiQBA=
    at WebSocketClient.failHandshake (/usr/local/lib/node_modules/homebridge-webos-tv/node_modules/websocket/lib/WebSocketClient.js:339:32)
    at WebSocketClient.validateHandshake (/usr/local/lib/node_modules/homebridge-webos-tv/node_modules/websocket/lib/WebSocketClient.js:326:14)
    at ClientRequest.handleRequestUpgrade (/usr/local/lib/node_modules/homebridge-webos-tv/node_modules/websocket/lib/WebSocketClient.js:261:14)
    at ClientRequest.emit (events.js:400:28)
    at Socket.socketOnData (_http_client.js:553:11)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
    at Socket.Readable.push (internal/streams/readable.js:204:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
[30/09/2021, 17:07:31] [homebridge-webos-tv] [LG TV] Message from TV 

[30/09/2021, 17:07:31] [homebridge-webos-tv] [LG TV]  {
  type: 'utf8',
  utf8Data: '{"type":"registered","id":"385827880000","payload":{"client-key":"bf631c7ffdfe30012d2ccea136e1f102"}}'
}
[30/09/2021, 17:07:31] [homebridge-webos-tv] [LG TV] Connected to TV
[30/09/2021, 17:07:31] [homebridge-webos-tv] [LG TV] Requesting TV information
[30/09/2021, 17:07:31] [homebridge-webos-tv] [LG TV] system service - getSystemInfo requested. 
[30/09/2021, 17:07:31] [homebridge-webos-tv] Child bridge process ended

**Comment by calvinyeap** [comment]
Ah ok. I believe I'm running on 32 at the moment. Not sure if below is the right way to check though. I have also checkec my config.json, I don't see any 64 bit flag as well.

pi@homebridge:/var/lib/homebridge $ uname -m
armv7l
pi@homebridge:/var/lib/homebridge $ getconf LONG_BIT
32

**Comment by merdok** [comment]
Ok, this does not look like 64 bit so at least we can exclude that!

But we still need to find out what exactly crashes the bridge, my suspicion is that might be one of the dependencies...

**Comment by DJay-X** [comment]
OMG... Good I had a look here. 
I'm running mad for hours now. I updated the plugin like I always do and didn't thought about when I left the home. Outside home I was wondering why nothing is working anymore.

However... Homebridge is now starting over and over. Nothing to see in the log.
Only `Homebridge Process Ended. Code: null, Signal: SIGBUS` and the restart begins again.
Back to 2.2.2 changed nothing. 

Node.js Version v14.18.0
Npm Version	v7.24.1

2nd-Instance on the same Raspberry is working finde.
But the main Homebridge that is not working now is mainly important. 
I hope you can help. Thanks in advance.

**Comment by TzachiGuetta** [comment]
maybe its realted to Node.js Version v14.18.0 ?  @merdok

**Comment by merdok** [comment]
Oh, it might also be related to the nodejs version. 
Could you guys try to downgrade nodejs to a lower version and try it out?

**Comment by DJay-X** [comment]
That was the first thing I did downgrade to Node 14.17.6 but that didn't help.

**Comment by idealdreams** [comment]
My logs do not look any different than what have been posted but wanted to provide a little more detail. 

The plug-in appears stable when the TV is off. When I turn the TV on, it prompts me to accept or decline the pairing request through LG connect. If I click no, nothing happens and Homebridge remains stable. 

If I select yes, the Homebridge service immediately restarts and when it comes back up, my TV asks me again if I’d like to pair. Selecting yes will cause another restart cycle. 

I’ve tried multiple versions of the plug-in and experience the same behavior each time so agreed that it sounds like an issue with one of the plug-in’s dependencies.

**Comment by DJay-X** [comment]
> The plug-in appears stable when the TV is off. 

Thanks for that hint. Same here. When the TV is off there is no restart loop.
LG Modell 55EG9209-ZA, Software 04.26.00, webOS 2.2.3-1351 (beehive-biscayne)

Though I don't get any prompt to accept or decline pairing.

**Comment by merdok** [comment]
What makes me think that this is definitely related to on of the dependencies is that for me everything runs fine and I did not update any of my dependencies since a long time. Besides you all report the same issue that even after downgrading the plugin to a previous version the issue is still there where before it was not there.

So the question is now which dependency it is🙃
Since you all tell that it happens after you accept the pairing request then my suspicion would be that it is something related to either the network connection or file writing. Whenever you accept the pairing request the key file should be created in the prefs directory, is that case or is the file not created?

**Comment by OrigSorceror** [comment]
I am thinking it must either be node or a dependent. I am having issues with another plugin too one that sends a login credentials to an external web server, that keeps reporting incorrect username or password (which are correct as i can log in to the web server with them).. 

Since i am doing a fresh rebuild. I might re-start the rebuild and install an older version of node and npm and see how that pans out. 

At this stage i am fresh out of ideas as to what is causing the issues.

**Comment by merdok** [comment]
You should try to downgrade node to version 13.x or even 12.x and see if that helps. I will later check which one I have installed...

**Comment by OrigSorceror** [comment]
Just for interest i had an old rapberry pi 3b hanging around and set that one up again with the old plugins and it is running node v14.17.1. and everything was working. so i started updating the plugins 
These are the plugins i have
Homebridge-Cbus
homebridge ring
homebridge camera FFMpeg
homebridge eufysecurity
homebridge wiz lan

and now it is failing again. looks like one of those plugin updates has change a dependent which is causing the issues..

**Comment by OrigSorceror** [comment]
no good i'm afraid.. even with a fresh install and only the CBus plugin installed it still loops homebridge..  unfortunately the fault is not only this plugin but the one by grzegorz as well. 
https://github.com/grzegorz914/homebridge-lgwebos-tv/issues/110

when it connects to the LG TV homebridge reboots..

**Comment by carlosgamezvillegas** [comment]
I don't know if this helps but this is what I get in the log window after I press to accept the connection in the TV

[9/30/2021, 9:47:38 AM] [webostv] [LG TV] Connected to TV
homebridge.service: Main process exited, code=killed, status=7/BUS
homebridge.service: Failed with result 'signal'.

Please let us know what we can help to solve this issue. This is one of the plugins I use the most.

Kind regards

**Comment by Garia666** [comment]
Like in my post,  the other webos plug-in has the same issues. The only thing different that it happens at the moment you accept the plug-in to control your tv.  Recently the tv received an update as well.

**Comment by merdok** [comment]
The problem here is that the error output for the issue is really bad or basically does not not exists... We can certainly say that one of the dependencies is the root cause here but the dependency needs to be identified. 
Can you guys please run this command `npm list -g --depth=2` which lists the used dependencies and post the results here:

```
├─┬ homebridge-webos-tv@2.2.2
│ ├─┬ lgtv2@1.6.3
│ │ ├── mkdirp@1.0.4
│ │ ├── persist-path@1.0.2
│ │ └── websocket@1.0.34
│ ├─┬ mkdirp@0.5.5
│ │ └── minimist@1.2.5
│ ├── tcp-ping@0.1.1
│ └── wake_on_lan@0.0.4
```

I think depth=2 should be enough for now.

BTW, i am still running on nodejs 12.22.4

**Comment by Garia666** [comment]
homebridge-lgwebos-tv@1.9.14
│ ├─┬ @mi-sec/wol@1.0.13
│ │ └── @mi-sec/mac-address@1.0.16
│ ├── tcp-ping@0.1.1
│ └─┬ websocket@1.0.34
│   ├─┬ bufferutil@4.0.4
│   │ └── node-gyp-build@4.3.0
│   ├─┬ debug@2.6.9
│   │ └── ms@2.0.0
│   ├─┬ es5-ext@0.10.53
│   │ ├─┬ es6-iterator@2.0.3
│   │ │ ├── d@1.0.1
│   │ │ ├── es5-ext@0.10.53 deduped
│   │ │ └── es6-symbol@3.1.3 deduped
│   │ ├─┬ es6-symbol@3.1.3
│   │ │ ├── d@1.0.1 deduped
│   │ │ └── ext@1.6.0
│   │ └── next-tick@1.0.0
│   ├─┬ typedarray-to-buffer@3.1.5
│   │ └── is-typedarray@1.0.0
│   ├─┬ utf-8-validate@5.0.6
│   │ └── node-gyp-build@4.3.0 deduped
│   └── yaeti@0.0.6

**Comment by OrigSorceror** [comment]
├─┬ homebridge-webos-tv@2.2.3
│ ├─┬ lgtv2@1.6.3
│ │ ├── mkdirp@1.0.4
│ │ ├── persist-path@1.0.2
│ │ └── websocket@1.0.34
│ ├─┬ mkdirp@0.5.5
│ │ └── minimist@1.2.5
│ ├── tcp-ping@0.1.1
│ └── wake_on_lan@0.0.4

**Comment by merdok** [comment]
I do not think that  utf-8-validate should have anything to do with that...
I kind of suspect it might be node-gyp-build, could some of you try to downgrade that one to like 4.2.3?

**Comment by OrigSorceror** [comment]
tried to downgrade it but no luck. 
I installed version 4.2.3 by using sudo npm install -g node-gyp-build@4.2.3 which shows up as a separate package in the node list. 
But 4.3.0 still appears under the lg web os package list. 
tried to uninstall that using sudo uninstall node-gyp.build@4.3.0 and get no such file or directory.  So it must be installed as part of the package for webOS, i do not know how to change it from within a package.

**Comment by merdok** [comment]
Yes, you should not install it using with the -g command which installs it globally. You have to navigate to the homebrige-webos-tv directory and the go to node_modules and there you have to navigate yourself through the lgtv2, websocket and bufferutils directories(they should again be in the node_modules directories) and there you execute the npm install command but without the -g parameter and that should work.

**Comment by OrigSorceror** [comment]
Successfully downgraded nod-gyp-build to 4.2.3
├─┬ homebridge-webos-tv@2.2.3
│ ├─┬ lgtv2@1.6.3
│ │ ├── mkdirp@1.0.4
│ │ ├── persist-path@1.0.2
│ │ └─┬ websocket@1.0.34
│ │   ├─┬ bufferutil@4.0.4
│ │   │ └── node-gyp-build@4.2.3 deduped
│ │   ├─┬ debug@2.6.9
│ │   │ └── ms@2.0.0
│ │   ├─┬ es5-ext@0.10.53
│ │   │ ├── es6-iterator@2.0.3
│ │   │ ├── es6-symbol@3.1.3
│ │   │ └── next-tick@1.0.0
│ │   ├─┬ typedarray-to-buffer@3.1.5
│ │   │ └── is-typedarray@1.0.0
│ │   ├─┬ utf-8-validate@5.0.6
│ │   │ └── node-gyp-build@4.2.3 deduped
│ │   └── yaeti@0.0.6
│ ├─┬ mkdirp@0.5.5
│ │ └── minimist@1.2.5
│ ├── node-gyp-build@4.2.3
│ ├── tcp-ping@0.1.1
│ └── wake_on_lan@0.0.4

Same issue though. after accepting the pairing on the TV, everything crashes and homebridge reboots. so node-gyp-build was not the cause.

**Comment by merdok** [comment]
Well then this package is not the issue... Did you btw try to downgrade nodejs to 12.x?

**Comment by OrigSorceror** [comment]
no as the package was working with node 14.17

**Comment by grzegorz914** [comment]
the problem is with bufferutil please downgrade to 4.0.3

**Comment by falinka** [comment]
> I don't know if this helps but this is what I get in the log window after I press to accept the connection in the TV
> 
> [9/30/2021, 9:47:38 AM] [webostv] [LG TV] Connected to TV homebridge.service: Main process exited, code=killed, status=7/BUS homebridge.service: Failed with result 'signal'.
> 
> Please let us know what we can help to solve this issue. This is one of the plugins I use the most.
> 
> Kind regards

Second that. As soon as you click "accept" on TV - it crashes, and loop starts.

**Comment by OrigSorceror** [comment]
success after downgrading bufferutil to 4.0.3 it is now working.. Had to re-add the TV to HomeKit but all is functioning again on Node 14.18.0

**Comment by OrigSorceror** [comment]
instructions to downgrade bufferutil from 4.0.4 to 4.0.3 
in SSH command window go to the root of the pi OS
type
cd /lib/node_modules/homebridge-webos-tv/node_modules
to get to the right directory then 
type
sudo npm install bufferutil@4.0.3
that will downgrade the package. 
run the setup and enter TV name, I.P, and MAC restart homebridge and it will now pair. 
you may need to remove the old instance of the TV from homekit on your iOS device or MAC, and re-add it using the homebridge QR code.

**Comment by merdok** [comment]
So it is indeed bufferutil which causes the issue...

**Comment by OrigSorceror** [comment]
sure is

**Comment by merdok** [comment]
The issue should now be resolve with version 2.2.4! Can you please try to update and let me know?

**Comment by OrigSorceror** [comment]
Nope it has gone back to rebooting homebridge

**Comment by OrigSorceror** [comment]
reverting bufferutil to version 4.0.3 fixes the rebooting as before

**Comment by merdok** [comment]
Dang, will do another and update you!

**Comment by OrigSorceror** [comment]
no worries

**Comment by merdok** [comment]
Try 2.2.5, now it should hopefully work...

**Comment by OrigSorceror** [comment]
that one appears to be working fine :)

**Comment by OrigSorceror** [comment]
i guess the next thing to figure out now that it has been fixed, is what caused bufferutil to break the plugin in the first place. Eventually (will take a while) but bufferutil 4.0.3 will eventually be deprecated, so hopefully the issue with 4.0.4 get rectified and does not get carried over to newer packages.

**Comment by merdok** [comment]
I will investigate that... Important for now is that the plugin is working now again!

**Comment by OrigSorceror** [comment]
yup

**Comment by falinka** [comment]
I confirm, all good with 2.2.5.

**Comment by OrigSorceror** [comment]
@merdok 
Cool thanks. Also confirming the new versions of both the bufferutil and the plugin are working 100%.  :)

**Comment by iCarl** [comment]
I am still having this exact issue

**Comment by merdok** [comment]
@iCarl either your `bufferutil` dependency is not up to date or you have a different issue.
