### ISSUE TITLE
I can't run the web os 3 this error pop ups

### ISSUE THREAD

**Issue by Shana611** [merdok/homebridge-webos-tv#41]
/usr/local/lib/node_modules/homebridge/lib/api.js:108
  if (name.indexOf('.') == -1) {
           ^
TypeError: Cannot read property 'indexOf' of undefined
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:108:12)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:314:45)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:85:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

**Comment by merdok** [comment]
Seems like an issue with your homebridge, maybe remove everything and try to install it again.

**Comment by Shana611** [comment]
Thank you for your reply. Homebridge runs perfectly without any error but after inastalling the WebOS 3 plug-in those errors pop up. Do I need do any settings on TV as well

**Comment by merdok** [comment]
Yes, but i don't see any reference to my plugin in this crash log, only to homebridge.  You need to do what is described in the Readme.

**Comment by Shana611** [comment]
But TV settings not in the Readme. I just want to do I need to do any settings on the TV as well. Thanks

**Comment by merdok** [comment]
From Readme:
> You also need to enable mobile tv on on your tv for the turn on feature to work correctly.
That is all what you need.
