### ISSUE TITLE
plugin does not retain configuration

### ISSUE THREAD

**Issue by scrinq** [merdok/homebridge-webos-tv#435]
Hi !

Thanks for the plugin !
I've installed it and tried configuring it. Unfortunately, the plugin does not seem to retain the configuration: every information I give it (TV name, IP, MAC...) is lost when I restart HomeBridge.
The logs do not say much:
[4/14/2022, 7:25:58 AM] ---
[4/14/2022, 7:25:58 AM] Loaded plugin: homebridge-webos-tv@2.2.7
[4/14/2022, 7:25:58 AM] Registering platform 'homebridge-webos-tv.webostv'
[4/14/2022, 7:25:58 AM] ---

I try and try again with the same result: back to initial state without configuration. What can I do ?

Couple of details:
- plugin: homebridge-webos-tv v2.2.7
- Homebridge: v1.4.0 (HAP v0.10.0)
- OS: Debian GNU/Linux Buster (10)
- Node.js: v17.9.0
- Npm: v8.5.5
- homebridge-config-ui-x: v4.42.0

Thanks a lot for your help !

**Comment by merdok** [comment]
Seems more like a homebridge or operating system problem to me. Everything what you entered in the config.json file has nothing to do with the plugin, the plugin just reads from there. Make sure you are allowed to make changes to the config.json and that it is not overwritten by something else.

**Comment by scrinq** [comment]
Yes, you are right: Homebridge is part of my home automation system (jeedom) and platforms and accessories are to be added using the interface provided by Jeedom. Else, configuration elements are overwritten. Now that I am able to modify the configuration, I have an other issue:
[4/17/2022, 11:29:07 AM] ---
[4/17/2022, 11:29:07 AM] Loading 4 platforms...
[4/17/2022, 11:29:07 AM] [Jeedom] Initializing Jeedom platform...
[4/17/2022, 11:29:07 AM] [Jeedom] debugLevel:400
[4/17/2022, 11:29:08 AM] [Config] Initializing config platform...
[4/17/2022, 11:29:08 AM] [Config] Spawning homebridge-config-ui-x with PID 9351
[4/17/2022, 11:29:08 AM] [webostv] Initializing webostv platform...
[4/17/2022, 11:29:08 AM] [Jeedom] Synchronisation Jeedom <> Homebridge...
[4/17/2022, 11:29:09 AM] [webostv] Init - initializing devices
[4/17/2022, 11:29:09 AM] [webostv] [tv salon] Init - got TV configuration, initializing device with name: tv salon
[4/17/2022, 11:29:09 AM] TypeError: The "path" argument must be of type string. Received undefined
at new NodeError (node:internal/errors:372:5)
at validateString (node:internal/validators:120:11)
at join (node:path:1172:7)
at module.exports (/usr/lib/node_modules/homebridge-webos-tv/node_modules/persist-path/index.js:19:22)
at new LGTV (/usr/lib/node_modules/homebridge-webos-tv/node_modules/lgtv2/index.js:48:16)
at LgTvController.setupLgtvInstance (/usr/lib/node_modules/homebridge-webos-tv/lib/LgTvController.js:152:17)
at LgTvController.connect (/usr/lib/node_modules/homebridge-webos-tv/lib/LgTvController.js:129:14)
at webosTvDevice.connectToTv (/usr/lib/node_modules/homebridge-webos-tv/index.js:167:19)
at new webosTvDevice (/usr/lib/node_modules/homebridge-webos-tv/index.js:153:10)
at webosTvPlatform.initDevices (/usr/lib/node_modules/homebridge-webos-tv/index.js:2235:11)
[4/17/2022, 11:29:10 AM] Got SIGTERM, shutting down Homebridge...

Any idea what that might be ?

Thanks again for your help,
Serge

**Comment by merdok** [comment]
You specified an empty value at one of the configuration fields, which is not allowed. I suppose it is the `keyFile` property.
