### ISSUE TITLE
mkdirp is not a function - restart loop

### ISSUE THREAD

**Issue by CharlieMK** [merdok/homebridge-webos-tv#446]
First time user here. After installing, I received the following error, resulting in a restart loop of Homebridge:

```
[09/08/2022, 07:10:17] [webostv] Init - initializing devices
[09/08/2022, 07:10:17] [webostv] [My LG TV] Init - got TV configuration, initializing device with name: My LG TV
[09/08/2022, 07:10:17] TypeError: mkdirp is not a function
    at new webosTvDevice (file:///usr/local/lib/node_modules/homebridge-webos-tv/index.js:141:7)
    at webosTvPlatform.initDevices (file:///usr/local/lib/node_modules/homebridge-webos-tv/index.js:2360:11)
    at HomebridgeAPI.emit (node:events:527:28)
    at HomebridgeAPI.signalFinished (/usr/local/lib/node_modules/homebridge/src/api.ts:275:10)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:190:14)
[09/08/2022, 07:10:17] Got SIGTERM, shutting down Homebridge...
```

Looking at https://github.com/merdok/homebridge-webos-tv/blob/71a3aa18725b40a16a9d2d53d55cdced6e7a4fcb/index.js#L141 the problem was fixed easily by manually creating the preferences directory (/var/lib/homebridge/.webosTv). 

Just adding this here for new users who may stumble upon the same issue. 

Running Homebridge v1.5.0 with node v16.16.0

**Comment by merdok** [comment]
Hi, thanks for letting me know. This was a bug in the latest update. Should now be fixed in version 2.3.1
