### ISSUE TITLE
Homebridge 2.0 Support

### ISSUE THREAD

**Issue by Quickstep3** [merdok/homebridge-webos-tv#537]
Homebridge 2.0 beta is out with some breaking changes - see: https://github.com/homebridge/homebridge/wiki/Updating-To-Homebridge-v2.0

WebOS-TV plugin fails to load with the following error:
[24/07/2024, 07:48:25] [homebridge-webos-tv] Restarting Process...
[24/07/2024, 07:48:26] [homebridge-webos-tv] Launched child bridge with PID 523
[24/07/2024, 07:48:27] Registering platform 'homebridge-webos-tv.webostv'
[24/07/2024, 07:48:27] [homebridge-webos-tv] Loaded homebridge-webos-tv v2.4.4 child bridge successfully
HAP-NodeJS WARNING: The accessory 'homebridge-webos-tv' has an invalid 'Name' characteristic ('homebridge-webos-tv'). Please use only alphanumeric, space, and apostrophe characters. Ensure it starts and ends with an alphabetic or numeric character, and avoid emojis. This may prevent the accessory from being added in the Home App or cause unresponsiveness.
[24/07/2024, 07:48:27] Loaded 0 cached accessories from cachedAccessories.0E1942AB2AF1.
HAP-NodeJS WARNING: The accessory 'homebridge-webos-tv CD7C' has an invalid 'Name' characteristic ('homebridge-webos-tv CD7C'). Please use only alphanumeric, space, and apostrophe characters. Ensure it starts and ends with an alphabetic or numeric character, and avoid emojis. This may prevent the accessory from being added in the Home App or cause unresponsiveness.
[24/07/2024, 07:48:27] [homebridge-webos-tv] Init - initializing devices
[24/07/2024, 07:48:27] [homebridge-webos-tv] [LG TV] Init - got TV configuration, initializing device with name: LG TV
TypeError: Cannot read properties of undefined (reading 'TELEVISION')
    at webosTvDevice.initTvAccessory (file:///usr/local/lib/node_modules/homebridge-webos-tv/index.js:287:95)
    at new webosTvDevice (file:///usr/local/lib/node_modules/homebridge-webos-tv/index.js:172:10)
    at webosTvPlatform.initDevices (file:///usr/local/lib/node_modules/homebridge-webos-tv/index.js:2592:11)
    at HomebridgeAPI.emit (node:events:518:28)
    at HomebridgeAPI.signalFinished (/usr/local/lib/node_modules/homebridge/src/api.ts:271:10)
    at ChildBridgeFork.startBridge (/usr/local/lib/node_modules/homebridge/src/childBridgeFork.ts:194:14)
[24/07/2024, 07:48:27] [homebridge-webos-tv] Child bridge process ended
[24/07/2024, 07:48:27] [homebridge-webos-tv] Process Ended. Code: 1, Signal: null

Just flagging so that the plugin can be updated in time for Homebridge 2.0

**Comment by merdok** [comment]
Thanks for the info. Will have a look at that!

**Comment by JasonGoldenDDT** [comment]
Receiving this message from Homebridge this morning: 

<img width="796" alt="Screenshot 2024-08-29 at 7 35 54 AM" src="https://github.com/user-attachments/assets/17474185-d02a-4217-b9ee-364d64c1d372">

**What support can this community provide to assist in the remediation of this plugin?**

**Comment by merdok** [comment]
Will be looking at that in the next days...

**Comment by merdok** [comment]
As of version 2.4.5, homebridge 2.0 should now be supported

**Comment by Quickstep3** [comment]
Can confirm this is fixed - Thanks
